// <auto-generated />
namespace Batibatlocation.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class asfjbaiga : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asfjbaiga));
        
        string IMigrationMetadata.Id
        {
            get { return "202503041039304_asfjbaiga"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
